import 'word_pair.dart';

// Temporary data for checking the continuous matching mechanics.
const testWords = [
  WordPair(id: 'apple', english: 'apple', russian: 'яблоко'),
  WordPair(id: 'house', english: 'house', russian: 'дом'),
  WordPair(id: 'water', english: 'water', russian: 'вода'),
  WordPair(id: 'book', english: 'book', russian: 'книга'),
  WordPair(id: 'sun', english: 'sun', russian: 'солнце'),
  WordPair(id: 'dog', english: 'dog', russian: 'собака'),
  WordPair(id: 'cat', english: 'cat', russian: 'кошка'),
  WordPair(id: 'car', english: 'car', russian: 'машина'),
  WordPair(id: 'tree', english: 'tree', russian: 'дерево'),
  WordPair(id: 'road', english: 'road', russian: 'дорога'),
  WordPair(id: 'food', english: 'food', russian: 'еда'),
  WordPair(id: 'friend', english: 'friend', russian: 'друг'),
  WordPair(id: 'milk', english: 'milk', russian: 'молоко'),
  WordPair(id: 'bread', english: 'bread', russian: 'хлеб'),
  WordPair(id: 'door', english: 'door', russian: 'дверь'),
  WordPair(id: 'window', english: 'window', russian: 'окно'),
  WordPair(id: 'school', english: 'school', russian: 'школа'),
  WordPair(id: 'city', english: 'city', russian: 'город'),
  WordPair(id: 'flower', english: 'flower', russian: 'цветок'),
  WordPair(id: 'stone', english: 'stone', russian: 'камень'),
  WordPair(id: 'bird', english: 'bird', russian: 'птица'),
  WordPair(id: 'fish', english: 'fish', russian: 'рыба'),
  WordPair(id: 'moon', english: 'moon', russian: 'луна'),
  WordPair(id: 'star', english: 'star', russian: 'звезда'),
  WordPair(id: 'sky', english: 'sky', russian: 'небо'),
  WordPair(id: 'rain', english: 'rain', russian: 'дождь'),
  WordPair(id: 'snow', english: 'snow', russian: 'снег'),
  WordPair(id: 'wind', english: 'wind', russian: 'ветер'),
  WordPair(id: 'fire', english: 'fire', russian: 'огонь'),
  WordPair(id: 'sea', english: 'sea', russian: 'море'),
  WordPair(id: 'river', english: 'river', russian: 'река'),
  WordPair(id: 'mountain', english: 'mountain', russian: 'гора'),
  WordPair(id: 'chair', english: 'chair', russian: 'стул'),
  WordPair(id: 'table', english: 'table', russian: 'стол'),
  WordPair(id: 'bed', english: 'bed', russian: 'кровать'),
  WordPair(id: 'hand', english: 'hand', russian: 'рука'),
  WordPair(id: 'eye', english: 'eye', russian: 'глаз'),
  WordPair(id: 'key', english: 'key', russian: 'ключ'),
  WordPair(id: 'bag', english: 'bag', russian: 'сумка'),
  WordPair(id: 'cup', english: 'cup', russian: 'чашка'),
];
